version: '3'
services:
  web: 
    build: .
    depends_on:
      - prisma
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: my-secret-42
        databases:
          default:
            connector: mongo
            uri: >-
              mongodb+srv://WithoutHands:Sasha080701@mycluster-qntjt.azure.mongodb.net/test?retryWrites=true&w=majority